name: health_tick
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/countdown_tick.mp3


